- DebugUtils/GTMMethodCheck.m
Extract the DL_info check before the loop because it doesn't depend on anything in the loop.
> Extract the DL_info check before the loop

- Foundation/GTMServiceManagement.c
Gestalt() is deprecated with a 10.8 deployment target.  Use the
recommended replacement when deploying to 10.8 and 10.9, and just
use a constant function when deploying to 10.10.
> GTMServiceManagement.c: Don't use Gestalt() when targeting 10.8+

- UnitTesting/GTMIPhoneUnitTesting.entitlements
Same as what is in UnitTesting/GTMIPhoneUnitTestMain.m.
> Provides a testing entitlements files.

- Foundation/GTMNSThread+Blocks.h
- Foundation/GTMNSThread+Blocks.m
- Foundation/GTMNSThread+BlocksTest.m
Reverts google/google-toolbox-for-mac#178
Undoing, found some folks that need `-stop`.
> Revert "Fix up a race condition in GTMSimpleWorkerThread"

- Foundation/GTMNSScanner+JSON.h
- Foundation/GTMNSScanner+JSONTest.m
Use NSJSONSerialization instead.
> Deprecate GTMNSScanner+JSON

- Foundation/GTMSystemVersion.h
- Foundation/GTMSystemVersionTest.m
Move to NSProcessInfo where appropriate.
> Add Deprecation Notices to GTMSystemVersion

- Foundation/GTMFileSystemKQueue.h
- Foundation/GTMFileSystemKQueue.m
- Foundation/GTMFileSystemKQueueTest.m
You should use libdispatch with a DISPATCH_SOURCE_TYPE_VNODE source.
> Deprecate GTMFileSystemKqueue.

- .travis.yml
Release should work now (fingers crossed)
> Enable release

- Foundation/GTMTimeUtils.h
- Foundation/GTMTimeUtils.m
- Foundation/GTMTimeUtilsTest.m
- GTM.xcodeproj/project.pbxproj
- GTMiPhone.xcodeproj/project.pbxproj
- GoogleToolboxForMac.podspec
Utilities for relatively common desire to know the launch time of an app, or the boot time of a device.
> Add GTMTimeUtils

- Foundation/GTMRegex.m
- Foundation/GTMRegexTest.m
Don't try to use more bytes then there are in the string.
> Fix issue found via asan

- README.md
> Fix Bazel support instructions

- Foundation/GTMLogger.h
- Foundation/GTMLogger.m
> Fix KVO-related race condition that could cause an overrelease of `GTMLogLevelFilter`.

- Foundation/GTMSystemVersion.h
- Foundation/GTMSystemVersion.m
The min macOS version has been above that for a while.
> Drop PPC references.

- GoogleToolboxForMac.podspec
This will be a new major version because a bunch of deprecated things have been
dropped.
> Bump version for a release.

- AppKit/GTMCarbonEvent.h
- AppKit/GTMCarbonEvent.m
- AppKit/GTMFadeTruncatingTextFieldCell.m
- AppKit/GTMIBArrayTest.m
- AppKit/GTMKeyValueAnimation.h
- AppKit/GTMKeyValueAnimation.m
- AppKit/GTMUILocalizer.h
- AppKit/GTMUILocalizer.m
- AppKit/GTMUILocalizerAndLayoutTweaker.m
- AppKit/GTMUILocalizerTest.m
- Foundation/GTMLightweightProxy.h
- Foundation/GTMLightweightProxy.m
- Foundation/GTMLightweightProxyTest.m
- Foundation/GTMLoggerRingBufferWriter.h
- Foundation/GTMLoggerRingBufferWriter.m
- Foundation/GTMLoggerTest.m
- Foundation/GTMNSFileHandle+UniqueName.h
- Foundation/GTMNSFileHandle+UniqueName.m
- Foundation/GTMNSObject+KeyValueObserving.m
- Foundation/GTMSQLite.h
- Foundation/GTMSQLite.m
- Foundation/GTMScriptRunner.h
- Foundation/GTMScriptRunner.m
- Foundation/GTMStringEncoding.h
- Foundation/GTMStringEncoding.m
- GTM.xcodeproj/project.pbxproj
- iPhone/GTMFadeTruncatingLabel.m
- iPhone/GTMUILocalizer.h
- iPhone/GTMUILocalizer.m
- iPhone/GTMUILocalizerTest.m
This should be just about everything but the logger files.
> Adopt `instancetype` of `id`.

- Foundation/GTMNSObject+KeyValueObserving.h
- Foundation/GTMNSObject+KeyValueObserving.m
> Add nullability annotation.

- Foundation/GTMSQLite.h
- Foundation/GTMSQLite.m
- Foundation/GTMSQLiteTest.m
Make one oom case just abort as things are already going to be in bad shape.
> Add nullability annotations for GTMSQLite.

- GTM.xcodeproj/project.pbxproj
- GTMiPhone.xcodeproj/project.pbxproj
- GoogleToolboxForMac.podspec
- Resources/Base/PrivacyInfo.xcprivacy
- Resources/Logger/PrivacyInfo.xcprivacy
Everything but Logger -
No api's called by these sources.
Logger -
GTMLogLevelFilter uses NSUserDefaults to get the user's filter level that should be applied.
> Add xcprivacy manifest info.

- UnitTesting/GTMGoogleTestRunner.mm
These were so long ago, no one should really be using them.
> Remove conditional Xcode version support.

- UnitTesting/GTMGoogleTestRunner.mm
This was an error in b83f1b8b8c7e58fd00db570a3ec9dafd27ee3696.
> Bring back property removed by accident.

- Docs/Development.md
- MODULE.bazel
- update_version.py
Also correct the version for Bazel, looks like we missed it last release.
Update the notes on how to make a release.
> Add version update script helper.

- Foundation/GTMLogger+ASL.m
- Foundation/GTMLogger+ASLTest.m
- Foundation/GTMLoggerTest.m
- GTM.xcodeproj/project.pbxproj
- GTMiPhone.xcodeproj/project.pbxproj
- Convert GTMLogger+ASL over to ARC
> Follow up the ARC work on other GTMLogger classes.

- .github/workflows/bazel.yml
- .github/workflows/cocoapods.yml
- .github/workflows/xcode.yml
- Ensure the lastest stable Xcode on the image is used.
- Run everything on the macos-15 image.
> Fix up CI config

- iPhone/GTMUIImage+Resize.m
There looks like scale wasn't taking into account in all cases, so reverting the change and it can be re-applied once everything is sorted out.
iPhone/GTMUIImage+ResizeTest.m is being left as updated since more tests were added, so this only reverts the iPhone/GTMUIImage+Resize.m changes from the following commits:
-  75a758184e798511ee61ca58d62552f984919357.
-  71eab236503f7713ca3123c4e7aef82d56bb5952.
-  c5ac5c25cfcbb15554f377a0b5cfda9fc245af56.
> Revert the changes to iPhone/GTMUIImage+Resize.m
