BuildingAndUsing.txt, GoogleToolboxForMac.podspec
This only adds a Podspec for some of the commonly-used pieces of GTM.
Currently, there are some issues with some of the subspecs. These subspecs are either commented-out or annotated with a TODO. The rest of the subspecs should be fine.
I tested this locally by referencing
There is currently no 2.0.0 tag. We can either change the version here, decide to cut a 2.0.0 release arbitrarily, or perhaps cut a beta release tag for testing and then do an actual 2.0.0 release.
=> Add a Podspec for GTM.

AppKit/GTMNSBezierPath+Shading.m, Foundation/GTMGeometryUtils.h, Foundation/GTMGeometryUtilsTest.m, UnitTesting/GTMSenTestCase.h
Remove GTMCGPointToNSPoint, GTMNSPointToCGPoint, GTMCGRectToNSRect, GTMCGSizeToNSSize
Note that Apple's NSGeometry.h sometimes defines
NSGEOMETRY_TYPES_SAME_AS_CGGEOMETRY_TYPES
so there's some reason to believe the CG and NS structs can compile incompatibly.
Fix a typo in GTMSenTestCase.h
=> Fix GTMGeometry builds on 64 bit OS X where CG and NS struct sizes may differ.

DebugUtils/GTMTypeCasting.h
Make GTM_STATIC_CAST(className, object) and GTM_DYNAMIC_CAST(className, object)
return objects that are type-casted to className *, instead of id. This enables
access to properties on the casted objects, e.g.
GTM_STATIC_CAST(NSString, object).length
which wouldn't work previously, since accessing .length on an id type
(correctly) results in a compiler error.
=> Improve the casing macros

GoogleToolboxForMac.podspec
This has come up on issues #130 and #138.
=> Add default_subspecs to help avoid testing code ended up in apps.

AppKit/GTMCarbonEvent.m, Foundation/GTMNSFileManager+Carbon.m, Foundation/GTMServiceManagement.c, Foundation/GTMSystemVersion.m, UnitTesting/GTMAppKitUnitTestingUtilities.m
Starting in the 10.6 SDK, the non-underscored and all-lowercase macro
names in <AssertMacros.h> were deprecated. In the 10.13 SDK shipping in
Xcode 9 beta 3 (but not previous betas of Xcode 9), Apple has made good
on its promise to eventually disable these names. Update GTM to use the
new underscored mixed-case names.
Provided that nobody needs to target anything older than the 10.5 SDK
anymore, this should be a safe change.
Aside from GTMCarbonEvent.m, which is used by Chrome, this change is
untested, and was made by mechanically replacing uses of the various
check, require, and verify macros found in GTM.
=> 10.13 SDK (and iOS 11 equivalent) compatibility for GTM

Foundation/GTMGeometryUtilsTest.m, Foundation/GTMRegex.m, UnitTesting/GTMSenTestCase.h, iPhone/GTMUIImage+Resize.m
In https://crbug.com/747643, a new version of Clang produces warnings
when attempting to format NSInteger as %zd (which is normally used for
ssize_t). Acquiesce by casting NSInteger to long and formatting using
%ld.
In the process, I audited all occurrences of %zd in GTM and found that
the remainder were being used to format size_t, which ought to use %zu,
so I’ve corrected those.
I also audited the existing uses of %zu and found them all to be
correct.
=> Cast NSInteger to long for formatting as %ld

Foundation/GTMNSString+HTML.m, Foundation/GTMNSString+HTMLTest.m
This pull request is to enable gtm_stringByUnescapingFromHTML to unescape number sequence above 65535, such as `&#128077;` (which is 👍).
=> Add support to unescape &#128077;

Foundation/GTMSQLiteTest.m, Foundation/GTMStackTraceTest.m
- Set up stack trace test just so we make sure we don't recurse. Right now it is too tight and breaks on every system release.
- SQLite's behavior is actually undefined in the case of sqlite3_errcode, so don't depend on it in a test.
=> Fix up some broken tests.

Foundation/GTMNSThread+Blocks.h, Foundation/GTMNSThread+Blocks.m, Foundation/GTMNSThread+BlocksTest.m
Basically a complete rewrite of GTMSimpleWorkerThread that should get rid of a race condition
when stopping tests and testing for "isExecuting/isFinished".
It does change the observed behaviour of GTMSimpleWorkerThread a little in that "start" no longer
blocks until the thread is starting, and we removed the unused "stop" method.
=> Fix up a race condition in GTMSimpleWorkerThread

XcodeConfig/subconfig/General.xcconfig
This was causing errors when building with Xcode 10 and XCTest.
XCTest defines a bunch of macros starting with _[A-Z] that were
setting off the error when building for the Mac.
=> Turn off reserved-id-macro warning.

GTM.xcodeproj/project.pbxproj
There were quotes around the test harness path in the project that was making
it so Xcode couldn't find it to run it.
=> Fix up testharness.

UnitTesting/GTMAppKitUnitTestingUtilities.h, UnitTesting/GTMFoundationUnitTestingUtilities.h
It should all be replaced with XCTestExpectations.
=> Deprecate runloop spinning functionality for tests.

Foundation/GTMNSThread+Blocks.h, Foundation/GTMNSThread+Blocks.m, Foundation/GTMNSThread+BlocksTest.m
There was a race between the thread being finished and
isFinished/isExecuting reporting correctly.
There may have also been a locking issue on older single processor phones.
=> Fixes up a race condition in GTMNSThread+Blocks

Foundation/GTMSignalHandler.h, Foundation/GTMSignalHandler.m, Foundation/GTMSignalHandlerTest.m, GTM.xcodeproj/project.pbxproj
This gets GTMSignalHandler working with libdispatch, and also marks it
as deprecated because it is probably easier just to write your own
version to call a block instead of the method invocation here.
This also makes the tests run again which hasn't been happening for
a long time AFAICT.
=> Fixed up GTMSignalHandler and deprecated it.

Foundation/GTMScriptRunnerTest.m
This check is very flaky from OS version to OS version and whether or not you are running under the debugger.
=> Remove flaky "clean environment" check.

Foundation/GTMNSDictionary+URLArguments.h, Foundation/GTMNSDictionary+URLArguments.m, Foundation/GTMNSDictionary+URLArgumentsTest.m, Foundation/GTMNSString+URLArguments.h, Foundation/GTMNSString+URLArgumentsTest.m
The URLArgument categories should be replaced with usages of NSURLComponents and NSURLItems.
=> Add deprecation warnings on URLArgument categories.

GTMDefines.h
These have been useless since macOS 10.5.
=> Remove GTM_FOREACH_* macros.

Foundation/GTMNSThread+BlocksTest.m
The changes here had a test looping 5 times with a 1 second wait trying to finish
in a 5 second window. That's a little too close for flakiness. Increased time out to
10 seconds.
=> Fix up timeout for test.

Foundation/GTMNSThread+BlocksTest.m
The block must execute before the test completes.
=> Fix up race in testPThreadName.

Foundation/GTMLightweightProxy.m
Pick off the selector natively handled first. NSProxy's base (on my
current OS atleast) will attempt to forward things, and the fact
that the LightWeight proxy then eats the forward where there is no
target objc seems to confuse things.
This all makes the unittests fail when run in release mode, so it
just generally seems safer to reorder this.
The footnote, is NSProxy really defines a class method for this, but
since LightweightProxy doesn't have a fixed class to check with, it
can't really provide that method.
=> Reorder testing of selectors.

Foundation/GTMNSThread+BlocksTest.m
Made an assumption about how runloops worked in all versions of iOS.
Appears it was wrong in 32 bit versions on single processor.
It appears a runloop can execute multiple inputs from an input source in a single cycle around the runloop which caused a test to fail.
(iOS 8.4 on iPhone4s simulator)
=> Fix up GTMNSThread+block test.

Foundation/GTMNSThread+BlocksTest.m
The helpers not mess with names, so this was actually testing Apple's
API, which does seem to have bugs/race conditions, so stop paying
attention to it.
=> Drop the thread name test.

UnitTesting/GTMSenTestCase.m
Let the library build cleaning in the modes folks should migrate, their code
will still get the warning using things.
=> Turn off the compiler warnings when building the sources.

GoogleToolboxForMac.podspec
Looking at what has changed since the last release:
https://github.com/google/google-toolbox-for-mac/compare/v2.1.4...master
There are two small fixes, but the rest is removing a few unused things and
the majority is marking things as deprecated that the System Frameworks now
provide. So bumping the minor version so folks can control when they adopt
this if they so wish.
=> Version bump for a release.

GTMiPhone.xcodeproj/project.pbxproj
Target configs needed to be set to static library so that stripping occurred correctly.
Unittest config was set as well.
=> Set target configurations correctly.

AppKit/GTMUILocalizer.m
This change makes GTMLocalizer use NSAccessibility when building for 10.10+
deployment targets.
I tested this change by:
1) Hacking the GTM Xcode project to build with a 10.10 deployment target, and
ignoring the other deprecated API uses;
2) Patching this GTM into the chromium tree (which does target 10.10) and
ensuring that it still builds
=> GTMLocalizer: use NSAccessibility on 10.10+ deployment targets

UnitTesting/GTMGoogleTestRunner.mm
In case `file_name()` happens to return null, the attempt to report a failure will end up crashing during setup, with a non-informative message like:
```
<unknown>:0: error: -[GTMGoogleTestRunner CleanupTest::DocumentSnapshotIsBlankAfterCleanup]
failed: caught "NSInvalidArgumentException", "*** +[NSString stringWithUTF8String:]: NULL cString"
```
Note: this PR doesn't address the root problem that leads to a null filename, but makes it more apparent.
=> Fix GTMGoogleTestRunner triggering "NULL cString" exception in NSString.

UnitTesting/GTMGoogleTestRunner.mm
It's possible that XCTestCase defaultTestSuite method is invoked more than once. Currently it has the side-effect of adding new methods to the class but doesn't check if they already exist. This change adds a check to only add new methods if they aren't implemented by the class or its superclass.
=> Fix failure due to adding the same method twice

Foundation/GTMStringEncoding.h
Fixes the auto-generated interface methods for the desired methods. The deprecated methods were causing conflicts in the generated interface of the newer methods that would add a zero-length tuple parameter.
Example of fix for `encode:error:`
Interface Before:
```
open func encode(_ data: Data!, error: ()) throws -> String
```
Calling Code Before:
```
do {
try encodedString = encoder.encode(self, error: ())
} catch let error as NSError {
print("Error: \(error.domain)")
}
```
Interface After:
```
open func encode(_ data: Data!) throws -> String
```
Calling Code After:
```
do {
try encodedString = encoder.encode(self)
} catch let error as NSError {
print("Error: \(error.domain)")
}
```
Closes google/google-toolbox-for-mac#248
=> GTMStringEncoding: Mark deprecated methods to fix parameters in Swift.

Foundation/GTMNSDictionary+URLArguments.m, Foundation/GTMNSFileHandle+UniqueName.m, Foundation/GTMNSScanner+JSON.m, Foundation/GTMNSString+HTML.m, Foundation/GTMNSString+XML.m, iPhone/GTMUIFont+LineHeight.m
This removes all the nonsense symbols for suppressing libtool warnings that we no longer need.
=> Remove obsoleted nonsense symbols for suppressing libtool warnings

GTMDefines.h
The string parameters in NSAssertionHandler's -handleFailureInFunction:… method are declared nonnull, but converting __PRETTY_FUNCTION__ and __FILE__ to NSString (via +[NSString stringWithUTF8String:] returns nullable, leading to warnings.
I don't know of any reason __PRETTY_FUNCTION__ or __FILE__ would ever fail to convert to UTF-8, but this deals with the warnings by explicitly handling the nil return case from stringWithUTF8String: by providing a static string.
Also adds a __builtin_expect() around the condition, as the intention is that the condition should never be true.
=> Avoid nullability compiler/clang-tidy warnings in _GTMDevAssert.

Foundation/GTMSQLite.m, Foundation/GTMSQLiteTest.m
Apparently earlier compilers took our `const structs` and put them into const
data for us so their lifetime was effectively equivalent to `static`. Some
change/optimization in 11.4.1 has moved to that not being the case. Explicitly
make the data structures `static`.
=> userdata structures need to exist for lifetime of hooks.

Foundation/GTMRegex.m
`NSData-bytes` returns a `const void *`. Cast it to a `const char *` before trying to use with a `%s` format specifier.
=> Add a missing void *-to-char * cast

Foundation/GTMRegex.h, Foundation/GTMRegex.m
Fixes an issue where in certain compilation situations you could get
undefined symbols errors out of GTMRegex.h. The solution is to define
these string constants in the GTMRegex.m file
```
undef: _kGTMRegexPatternErrorErrorString
undef: _kGTMRegexPatternErrorPattern
undef: _kGTMRegexErrorDomain
Undefined symbols for architecture x86_64:
  "_kGTMRegexPatternErrorErrorString", referenced from:
      -[GTMRegex initWithPattern:options:withError:] in libRegex.a(GTMRegex.o)
  "_kGTMRegexPatternErrorPattern", referenced from:
      -[GTMRegex initWithPattern:options:withError:] in libRegex.a(GTMRegex.o)
  "_kGTMRegexErrorDomain", referenced from:
      -[GTMRegex initWithPattern:options:withError:] in libRegex.a(GTMRegex.o)
ld: symbol(s) not found for architecture x86_64
```
=> Fix for undefined symbols errors in GTMRegex.h

Foundation/BUILD, UnitTesting/BUILD, iPhone/BUILD
Thanks again, @maxwellE for the great work in #280! This is just a quick patch to make targets visible for outside use.
Could I get a review @thomasvl?
=> Bazel BUILD: Make targets corresponding to pod suspsecs publicly visible and usable.

Foundation/GTMURLBuilder.h, Foundation/GTMURLBuilder.m
This allows compilation with `-Woverriding-method-mismatch`.
=> Fix up isEqual so the parameter is `id` as declared in NSObject.

UnitTesting/GTMGoogleTestRunner.mm
-[XCTestCase recordFailureWithDescription:inFile:atLine:expected:] is deprecated, and the replacement is recordIssue:
=> Use new recordIssue: API

GoogleToolboxForMac.podspec
This is due to some of the subspec being only for some platforms, so they
otherwise were repeating the information.
=> Use constants so updating mins is a little easier.

AppKit/GTMCarbonEventTest.m, UnitTesting/GTMAppKitUnitTestingUtilities.h, UnitTesting/GTMAppKitUnitTestingUtilities.m
Impl was dependent on some APIs deprecated in 10.9, and at this point with all
the OS changes since then, it might not even be detecting things correctly.
=> Drop the ScreenSaver check.

Foundation/GTMScriptRunner.h, Foundation/GTMScriptRunner.m, Foundation/GTMScriptRunnerTest.m
With Apple no longer bundling python2, seems better not to generally provide
helpers that might require devtools to be installed.
Bash is also no longer the default shell, and while lots of script would likely
fail without it, seems safer to also just drop that helper too.
Update the tests to use a simpler shell where possible, the one test using
python to validate buffer handling is updated to try and find an installed
python, but it is only a testing dependency, so seems safe for now.
=> Drop the helper for python, perl, and bash runners.

UnitTesting/GTMGoogleTestRunner.mm
GTEST_FLAG_SET is provided for portability of set parameters, as the actual contents may differ. For more information, see:
https://github.com/google/googletest/blob/main/googletest/include/gtest/internal/gtest-port.h#L2206
https://github.com/google/googletest/blob/main/googletest/include/gtest/internal/gtest-port.h#L2249
Note the second implementation matches what's done here, whereas the first is for binaries that include ABSL.
=> Use GTEST_FLAG_SET instead of ::testing::GTEST_FLAG

DebugUtils/GTMSynchronizationAsserts.m
Add __unused attribute to variables used only inside assert blocks, in order to fix -Wunused-variable warning
=> Add __unused attribute to variables

Foundation/GTMGeometryUtils.h
Looks like in some newer Xcodes, Swift modules would prefer is CoreGraphics was imported instead of just Foundation.
=> Always import CoreGraphics.

Foundation/GTMNSFileManager+Path.h, Foundation/GTMNSFileManager+PathTest.m
Don't really want nil on the directory, but keep the support/testing for safety sake.
=> Add nullability annotations.

Foundation/GTMLogger+ASL.h, Foundation/GTMLogger+ASL.m, Foundation/GTMLogger.h
Now that things use `instancetype` the naming of some apis is better, this tweaks the names of the other apis that didn't change via the importer to remain aligned with the new style.
=> Add some Swift names.

Foundation/GTMNSString+HTML.h, Foundation/GTMNSString+HTML.m, Foundation/GTMNSString+XML.m
Also make memory errors fatal since odds are other things would choke if things are that close.
=> Add nullability to string+html.

iPhone/GTMFadeTruncatingLabel.m
The `ceil` calls were added back when updating things for iOS 7, to model what the older `-sizeWithFont:` call did. But looking back, Apple likely moved off the api (and behavior) with the adoption of retina screens, so we should do the fade calc based on the fractional sizes also, so we don't force a fade when the string fully fits.
=> Drop the `ceil` calls.

.github/workflows/main.yml, BUILD, DebugUtils/BUILD, Foundation/BUILD, USING.md, UnitTesting/BUILD, WORKSPACE, bazel_support/repositories.bzl, iPhone/BUILD
=> Bazel: Improve dependency situation per #410

WORKSPACE
Re-enables easier local debugging for people depending on GTM via the traditional WORKSPACE route.
[Sorry this is late-breaking. This bit of polish occurred *just* after you'd merged, but I thought it was still worthwhile to help you get high quality PRs.]
=> Re-add (blank) WORKSPACE

GoogleToolboxForMac.podspec
Since the repo has remove deprecated apis and moves some things from `id` to `instancetype` this could be source breaking to some folks, so major version change is called for.
=> Bump major version instead.

.bazelrc, BUILD, MODULE.bazel
bzlmod is now enabled by default. Follows up on #412, cleaning things up :)
(Hopefully the GitHub images have been updated to 7.0 and the tests will pass. If not, maybe rerun in a month--still worth my posting the PR, I think, so we don't forget to do this cleanup at some point.)
Cheers,
Chris
=> Delete .bazelrc now that Bazel 7 is released

.github/workflows/main.yml
The base images are advanced enough that these don't need to be controlled any more.
=> Stop forcing Xcode versions

.github/workflows/main.yml
This should help catch/validate things as the runners update with new Xcodes, etc.
=> Add scheduled CI runs to ensure things stay working.

Foundation/BUILD, Foundation/GTMLogger.m, GoogleToolboxForMac.podspec
Convert GTMLogger.m to use Automatic Reference Counting (ARC). Also, updates to the BUILD file and the podspec to reflect ARC compilation.
=> GTMLogger: Convert to ARC
